services:
  # --- Banco de Dados (Compartilhado mas segregado) ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      # O script init.sql criará os bancos específicos
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Executa o script de criação dos bancos ao iniciar
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- API 01: GO (Golang) ---
  api_go:
    build: ./go_api
    depends_on:
      db:
        condition: service_healthy
    # ESCALABILIDADE: Sobe 2 instâncias do container Go
    deploy:
      replicas: 2
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=users_go
    networks:
      - app_network

  # --- API 02: Python (FastAPI) ---
  api_python:
    build: ./python_api
    depends_on:
      db:
        condition: service_healthy
    # ESCALABILIDADE: Sobe 2 instâncias do container Python
    deploy:
      replicas: 2
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=users_python
    networks:
      - app_network

  # --- Gateway (Load Balancer) ---
  gateway:
    image: nginx:alpine
    depends_on:
      - api_go
      - api_python
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:80" # Acessaremos via http://localhost:4000
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge